[package]
name = "noir-binius-sp1-guest"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace]
resolver = "3"

[dependencies]
noir-binius-verifier = { path = "../../crates/noir-binius-verifier" }
sha2 = "0.10.9"
sp1-zkvm = { version = "=6.6.0" }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
