export {
  BINIUS_ZK_PROOF_TYPE,
  BiniusBackend,
  BiniusBackendError,
  type BiniusBackendOptions,
  type BiniusProofOptions,
  type ProofData,
  type RecursiveProofArtifacts,
  type SolidityVerifierOptions,
  type SolidityVerifierTarget,
  type DirectVerifierAbi,
  type VerifierDeployment,
  type VerifierDeploymentOptions,
  withVerifierProgram,
} from './backend.js';
